# Generated by Django 6.0.5 on 2026-05-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeServices_app", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
